name: Build Executable

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Compilazione C++ con MinGW
      run: |
        g++ main.cpp -o virus.exe -mwindows

    - name: Carica il file .exe come Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Virus-Executable
        path: virus.exe
